#
#   WD-Litebans - A WaterDogPE plugin that attempts at being fully compatible with litebans
#   Copyright (C) 2021  Funniray
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   I am available for any questions/requests: funniray10@gmail.com
#

###############################################################################################################
###############################################################################################################
####                                                                                                       ####
####                               IF YOU PAID FOR THIS, YOU WERE SCAMMED                                  ####
####                                     THIS IS A FREE PLUGIN                                             ####
####                           https://github.com/funniray/waterdog-litebans                               ####
####                           Report scammers to beingscammed@reallyisnt.fun                              ####
####                                                                                                       ####
###############################################################################################################
###############################################################################################################

showpiracywarning: true

jdbcurl: "jdbc:mysql://localhost:3306/litebans"
dbusername: "root"
dbpassword: ""

#This statement may cause issues on MySQL 5.7 or MariaDB versions less than 10.2.2
#If it is, disable this option.

#See https://github.com/funniray/waterdog-litebans/issues/2
checkAlts: true

#You should change this for each proxy running the server
servername: litebans
serveruuid: f15b78eda7294493b847f54b2005dd2e

#Messages
SilentPrefix: "[Silent] "
BanMessage: >-
  You have been banned on network.
    Reason: %1$s
    Punished By: %2$s
    Duration: %3$s
  You may appeal your ban at https://example.com
BanJoinMessage: "%s tried to join, but they were banned."
BanIPJoinMessage: "%s tried to join, but they were ipbanned."
BanBroadcast: "Player %1$s was banned by %2$s for %3$s duration: %4$s"
MuteBroadcast: "Player %1$s was muted by %2$s for %3$s duration: %4$s"
WarnBroadcast: "Player %1$s was warned by %2$s for %3$s"
KickBroadcast: "Player %1$s was banned by %2$s for %3$s"